version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange-rates
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: